### ISSUE TITLE
Not clear on how to apply license

### ISSUE THREAD

**Issue by gwhorley** [CloudBoltSoftware/vagrant#1]
The Readme simply states that I should open my browser to localhost:8443 then open another URL to request a license. No problem, except that the license I received by e-mail is an encoded string and the Cloudbolt web UI requires a license file. If I try to paste the string into a file and upload it, I get "The contents of the license file are malformed". The [install guide](http://docs.cloudbolt.io/installation.html) simply states that I open the web UI and upload the license. How am I supposed to apply this license string?

**Comment by ack81** [comment]
It seems we have not upgraded our vagrant box to the latest version of CB.  The previous license was a generated file.  The new version of CB will accept the license string that you have.  You can easily upgrade it with the following commands and try your license again.

vagrant ssh
sudo su -
wget http://downloads.cloudbolt.io/cloudbolt-upgrader-latest.tgz
tar xvzf cloudbolt-upgrader-latest.tgz
cd <to the cloudbolt_upgrader dir>
./upgrade_cloudbolt.sh

Please let us know if this resolves your issue and we will work on upgrading the vagrant box for a permanent fix.

**Comment by gwhorley** [comment]
Thanks, that helped! FYI there is a typo in the Readme now where cloudbolt is misspelled in one of the steps.
